language: go
go:
  - "1.11.x"

env:
  - GO111MODULE=on

services:
  - docker

# Build branches only when merging to master
branches:
  only:
    - master

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic -race ./...
  - make image
  - make dev-image

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make publish-images
